_title: Lesson 1 - Introduction
pages:
- title: Overview
  content: |
    This is a first lesson of keyboard touch typing. In this lesson we
    will provide information which will help you with teaching course.
  content2: |
    Press <Enter> to continue
- title: Coursor
  content: |
    When you press a key, new letter appears. Next letter will appear
    at possition one place forward. Place where next letter will appear
    is shown by special (ussualy blinking) symbol, called - "cursor"
    This is how cursor could look like - 
  content2: |
    Press <Enter> to continue
- title: Coursor
  content: |
    When cursor is shown on screen, that means computer wait for you
    to enter text.
    To see how it's look, press three character keys a, s, d.
    Do not care about tehnic now. We will concentrate on that later.
  content2: |
    Enter three characters

