name: build-release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-macos:
    name: build-macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin
      - run: cargo build --release --target=aarch64-apple-darwin
      - run: mv target/release/raiti/raiti.dmg raiti-aarch64-apple-darwin
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            raiti-aarch64-apple-darwin
            data/**

  build-linux:
    name: build-linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu
      - run: sudo apt-get update
      - run: sudo apt-get install -y libasound2-dev
      - run: cargo build --release --target=x86_64-unknown-linux-gnu
      - run: mv target/x86_64-unknown-linux-gnu/release/raiti raiti-x86_64-unknown-linux-gnu
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            raiti-x86_64-unknown-linux-gnu
            data/**

