name: build-release

permissions:
  contents: write

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:

  build-windows:
    name: build-windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
            toolchain:
              stable-x86_64-pc-windows-msvc
            targets: x86_64-pc-windows-msvc
      - run: cargo build --release --target=x86_64-pc-windows-msvc
      - run: mv target/x86_64-pc-windows-msvc/release/raiti.exe raiti-x86_64-pc-windows-msvc.exe
      - name: Create ZIP
        run: |
          Compress-Archive -Path raiti-x86_64-pc-windows-msvc.exe, data -DestinationPath raiti-x86_64-pc-windows-msvc.zip
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            raiti-x86_64-pc-windows-msvc.zip

  build-macos:
    name: build-macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin
      - run: cargo build --release --target=aarch64-apple-darwin
      - run: mv target/aarch64-apple-darwin/release/raiti raiti
      - run: tar czf raiti-aarch64-apple-darwin.tar.gz data raiti
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            raiti-aarch64-apple-darwin.tar.gz

  build-linux:
    name: build-linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu
      - run: sudo apt-get update
      - run: sudo apt-get install -y libasound2-dev
      - run: cargo build --release --target=x86_64-unknown-linux-gnu
      - run: mv target/x86_64-unknown-linux-gnu/release/raiti raiti
      - run: tar czf raiti-x86_64-unknown-linux-gnu.tar.gz data raiti
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            raiti-x86_64-unknown-linux-gnu.tar.gz
